identifier: l9rct699q19cg3k6
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /home/altee/Projects/my-blog
distFolder: dist/my-blog
outDir: /home/altee/Projects/my-blog/dist/static
handle404: ''
allowErrorCollect: false
